# Generated by Django 3.0.4 on 2020-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photos',
            field=models.ImageField(null=True, upload_to='recipes/'),
        ),
    ]
